# Default values for progress-service.
replicaCount: 1

strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0

image:
  repository: aswin018/k8s_mern_app_progress-service
  tag: v3
  pullPolicy: IfNotPresent

container:
  name: progress-service

service:
  type: ClusterIP
  port: 5005
  targetport: 5005

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5005
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5005
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /health
    port: 5005
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30

env:
  - name: PORT
    value: "5005"
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-secret
        key: progress-db-uri
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: auth-service-secret
        key: jwt-secret
  - name: REDIS_HOST
    value: "redis"
  - name: REDIS_PORT
    value: "6379"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

trivy:
  enabled: false
  severity: HIGH,CRITICAL
  scanType: fs
  ignoreUnfixed: false
