# Default values for workout-service.
replicaCount: 1

strategy:
  type: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0

image:
  repository: aswin018/k8s_mern_app_workout-service
  tag: v3
  pullPolicy: IfNotPresent

container:
  name: workout-service

service:
  type: ClusterIP
  port: 5003
  targetport: 5003

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

startupProbe:
  httpGet:
    path: /health
    port: 5003
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30

env:
  - name: PORT
    value: "5003"
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: mongodb-secret
        key: workout-db-uri
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: auth-service-secret
        key: jwt-secret

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

trivy:
  enabled: false
  severity: HIGH,CRITICAL
  scanType: fs
  ignoreUnfixed: false
