apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fit-forge
  labels:
    app.kubernetes.io/part-of: fit-forge
    app.kubernetes.io/component: database
type: Opaque
stringData:
  mongodb-root-password: root@123

  mongodb-auth-password: auth@123
  mongodb-nutrition-password: nutrition@123
  mongodb-progress-password: progress@123
  mongodb-workout-password: workout@123
  mongodb-user-password: user@123

  mongodb-metrics-password: metricsuser@123
  mongodb-replica-set-key: replicaset@123

  # Connection URIs for Microservices
  auth-db-uri: "mongodb://root:root@123@mongo-mongodb.fit-forge.svc.cluster.local:27017/auth_db"
  user-db-uri: "mongodb://root:root@123@mongo-mongodb.fit-forge.svc.cluster.local:27017/user_db"
  workout-db-uri: "mongodb://root:root@123@mongo-mongodb.fit-forge.svc.cluster.local:27017/workout_db"
  nutrition-db-uri: "mongodb://root:root@123@mongo-mongodb.fit-forge.svc.cluster.local:27017/nutrition_db"
  progress-db-uri: "mongodb://root:root@123@mongo-mongodb.fit-forge.svc.cluster.local:27017/progress_db"