apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fit-forge
  labels:
    app.kubernetes.io/part-of: fit-forge
    app.kubernetes.io/component: database
type: Opaque
stringData:
  mongodb-root-password: root@123

  mongodb-auth-password: auth@123
  mongodb-nutrition-password: nutrition@123
  mongodb-progress-password: progress@123
  mongodb-workout-password: workout@123
  mongodb-user-password: user@123

  mongodb-passwords: "auth@123,user@123,workout@123,nutrition@123,progress@123"

  mongodb-metrics-password: metricsuser@123
  mongodb-replica-set-key: replicaset@123

  # Connection URIs for Microservices (using separate users for each DB)
  auth-db-uri: "mongodb://auth_user:auth%40123@mongo-mongodb.fit-forge.svc.cluster.local:27017/auth_db"
  user-db-uri: "mongodb://user_user:user%40123@mongo-mongodb.fit-forge.svc.cluster.local:27017/user_db"
  workout-db-uri: "mongodb://workout_user:workout%40123@mongo-mongodb.fit-forge.svc.cluster.local:27017/workout_db"
  nutrition-db-uri: "mongodb://nutrition_user:nutrition%40123@mongo-mongodb.fit-forge.svc.cluster.local:27017/nutrition_db"
  progress-db-uri: "mongodb://progress_user:progress%40123@mongo-mongodb.fit-forge.svc.cluster.local:27017/progress_db"